version: '3.9'

services:
  gateway:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - bff-mail

  bff-mail:
    build: .
    env_file:
      - .env.example
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bff-mail.rule=PathPrefix(`/`)"
      - "traefik.http.services.bff-mail.loadbalancer.server.port=3000"

  worker:
    build: .
    command: ["node", "dist/worker.js"]
    env_file:
      - .env.example
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: bff_mail
      POSTGRES_USER: bff_mail
      POSTGRES_PASSWORD: bff_mail
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
